name: Hello World Workflow

on:
  push:
    branches:
      - main

env:
  E2E_CONTAINER: rainerk123/e2etesting:v0.3

  AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}

  SP_TENANT_ID: ${{ secrets.SP_TENANT_ID }}
  SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
  SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
  SP_SITE_ID: ${{ secrets.SP_SITE_ID }}

  SP_COMMAND_LIMITS_LIST_ID: ${{ secrets.SP_COMMAND_LIMITS_LIST_ID }}
  SP_BLOCK_COMMANDS_LIST_ID: ${{ secrets.SP_BLOCK_COMMANDS_LIST_ID }}

  

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create certificate files
        shell: bash
        run: |
          mkdir -p lib/certs

          cat > lib/certs/CST-E2E-1.cert.pem <<'EOF'
          ${{ secrets.MQTT_CERT_PEM }}
          EOF

          cat > lib/certs/CST-E2E-1.private.key <<'EOF'
          ${{ secrets.MQTT_PRIVATE_KEY }}
          EOF

          cat > lib/certs/AmazonRootCA1.pem <<'EOF'
          ${{ secrets.MQTT_ROOT_CA }}
          EOF
      - name: Verify cert files
        shell: pwsh
        run: |
          Get-ChildItem ./lib/certs

      - name: Verify environment variables
        shell: pwsh
        run: |
          if (-not $env:AWS_ENDPOINT) {
            throw "AWS_ENDPOINT is missing"
          }

          Write-Host "AWS_ENDPOINT is set. Length: $($env:AWS_ENDPOINT.Length)"

      - name: Check AWS endpoint DNS
        shell: pwsh
        run: |
          docker run --rm `
            -e AWS_ENDPOINT `
            $env:E2E_CONTAINER `
            sh -c 'echo "$AWS_ENDPOINT"'

      - name: Inspect AWS endpoint inside container
        shell: pwsh
        run: |
          docker run --rm `
            -e AWS_ENDPOINT `
            $env:E2E_CONTAINER `
            python -c "import os; print('[' + repr(os.getenv('AWS_ENDPOINT')) + ']')"

      - name: Run Robot Tests
        shell: pwsh
        run: ./scripts/Magic2.ps1